### ISSUE TITLE
Questions on how to use Pylenium from beginner

### ISSUE THREAD

**Issue by MaksimZinovev** [ElSnoMan/pyleniumio#122]
Firstly , thank you for such a great tool. I read docs and watched some tutorial videos. I think the best thing about Pylenium is that it streamlines set up and makes it possible to write much more concise code compared to Selenium out of the box.

I am beginner and learning programming/test automation is quite challenging  for me... I installed Pylenium and  tried to write  short test but could not make it working. I'd appreciate it if you could answer the questions below:

1. What's wrong with that test?  I tried to repeat steps that I perform when test search manually, but it seems like I am missing something:
```

from selenium.webdriver.common.keys import Keys
import time


def test_flatmates_search(py):
    py.visit('https://flatmates.com.au/')
    py.get('.styles__mainHeading___3wzRg').click()
    py.get('.hiddenInput').type('hornsby, 2077', Keys.ENTER)
    py.get('button[type="submit"]').click()

    # validate that title in search results contains search query
    assert py.get('h1[class="styles__searchHeading___LfuWW"]').should().contain_text("Redfern")
    assert py.get('h1[class="styles__searchHeading___LfuWW"]').should().contain_text("Rooms for Rent")

# output:

tests/test_fm.py:5 (test_flatmates_search)
test_fm.py:13: in test_flatmates_search
    assert py.get('h1[class="styles__searchHeading___LfuWW"]').should().contain_text("Redfern")
../venv/lib/python3.8/site-packages/pylenium/element.py:483: in contain_text
    raise AssertionError(f'Expected ``{text}`` to be in ``{self._element.text()}``')
E   AssertionError: Expected ``Redfern`` to be in ``Rooms for Rent``

Assertion failed
```

2.  I read in docs  that  one of the features  of Pylenium is "Automatic waiting and synchronization". What does that mean? 
Do we still need to use waits like this? 
```
py.wait(use_py=True).until(lambda x: x.find_element_by_id('.menu')).hover()
# or
py.wait(use_py=True).until(lambda x: x.find_element_by_id('.menu')).click()
```
3. Is it possible to extend/modify standard Pylenium method ? How it can be emplemented? For example, lets say I want to have modified py.get() method which executes this line before returning element:

"py.wait().until(lambda x: x.find_element_by_class_name('classname').is_displayed())" 

4.  Is it possible to change scope of "py" fixture so that we could use the same web driver instance to run all tests in module? Currently after each test browser window is closed and new window is initialised which requires additional time.

5. How can I test autocompletion in the above example? 

![Screenshot 2020-07-27 21 37 49](https://user-images.githubusercontent.com/53397443/88537763-7e699b00-d051-11ea-918b-6fab2eac8b04.png)

**Comment by ElSnoMan** [comment]
@MaksimZinovev First of all, thank you for trying out Pylenium! I'm glad you're liking it 😄 . Also, thank you for reaching out with your questions. I will do my best to answer them here, but feel free to also ping me on Slack groups like the Ministry of Testing or Test Automation University.

1.  The error looks correct here. The error is telling you that `"Rooms for Rent"` does not contain the word `"Redfern"` which is true. You can see that in the error message:

```
    assert py.get('h1[class="styles__searchHeading___LfuWW"]').should().contain_text("Redfern")
    raise AssertionError(f'Expected ``{text}`` to be in ``{self._element.text()}``')
E   AssertionError: Expected ``Redfern`` to be in ``Rooms for Rent``
```

I don't know the Application Under Test (AUT), but it seems you need to change the selector in the first assertion.

2. There is quite a bit of waiting that will happen automatically when using Pylenium. By default, all of the locating functions (like `.get()`, `.find()`, `.getx()`, etc.) will automatically wait for the element to be available in the DOM. You can also use the `.should()` API to wait for certain expectations to be true. For example:

```python
# wait until the Page Title contains the word "foo"
py.should().contain_title('foo')

---or---

# wait until the element is visible
py.get('#button').should().be_visible()
```

However, this doesn't mean that you won't need _any_ custom waits. I'm willing to bet that you will still need to synchronize with certain things in your web application. Pylenium makes this really easy for you! Like I said before, you can leverage the `.should()` API, or you can use the `.wait()` API to create your own, custom conditions.

For example, maybe you want to wait until an element has a specific color. That is a "niche" thing to wait for so I wouldn't add it to Pylenium natively, but you can still create the custom condition easily:

```python
def wait_for_element_to_have_color(element, color) -> Element:
    """ Reusable condition to wait for the element to have the given RGBA color """
    py.wait().until(lambda _: element.css_value('color') == color)
    return element

def test_element_changes_color(py):
    py.visit('https://random-page.com')
    py.get('#button').click()
    element_to_change = py.get('#avatar')
    assert wait_for_element_to_have_color(element_to_change, 'rgba(123, 123, 123, 1)')
```

3. You can always write your own functions that wrap Pylenium functionality. Just define the function somewhere and then use it. Using your example:

```python
def element_by_class_name_is_displayed(class_name) -> bool:
    """ Check that the element is displayed given its class name. """
    return py.wait().until(lambda x: x.find_element_by_class_name('classname').is_displayed())
```

4. Although you can, this is not recommended. Tests should be modular and atomic. You should not want to share a driver between tests. This is a really bad practice and even an anti-pattern! Please don't do this. Instead, try to figure out other ways to speed up your tests like running tests in parallel or creating seams or "shortcuts" using HTTP Requests, etc.

5. Without seeing any HTML, I can't really help you here.

**Comment by MaksimZinovev** [comment]
@ElSnoMan thank you for answers! 

**regarding # 2** 

I understand that  I can write my own functions, but what I was asking if I can I modify Pylenium methods or add my own method so that I can chain them with existing Pylenium methods. 

For example. I've got this test which fails due to StaleElementReferenceException in  this line 
``` py.get('div > h1').should().contain_text('Redfern')``` . 
It would be helpful to be able to create my own get() method (using standard get() as basis) with ingored exception and retry mechanism, something like this:

```
py.get('div > h1').should().contain_text('Redfern') 

--- output ---

test_fm.py:131: in test_flatmates_listing
    py.get('div > h1').should().contain_text('Redfern')
    ...
E   selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document

--- this fixes the problem -- 

   try:
        py.get('div > h1').should().contain_text('Redfern')
    except:
        time.sleep(.1)
        py.get('div > h1').should().contain_text('Redfern')

--- this would fixed the problem in more elegant way? -- 
       
 py.get_ignore_exception_then_retry('div > h1').should().contain_text('Redfern')


```

**regarding # 4**

> Although you can, this is not recommended. Tests should be modular and atomic. You should not want to share a driver between tests. This is a really bad practice and even an anti-pattern! Please don't do this. Instead, try to figure out other ways to speed up your tests like running tests in parallel or creating seams or "shortcuts" using HTTP Requests, etc.

I understand that we should isolate tests from each other, even  though initialising browser can take up to 40-60% test time and we have tens or hundreds of tests. Or sometimes we have multiple tests which require  login step which will take even longer time. We still should not share driver between these tests and keep them modular (in this case each time start from logging in), correct?

What if I want to implement end-2-end test with multiple actions which real users will be  likely performing (for example, visit page, search listing, click on listing, add to cart, find another listing, add to cart, go to checkout, complete checkout)?  Is it ok to include multiple assertions along the path?

**Comment by ElSnoMan** [comment]
# Section 1

try/except should be a "last resort" because:

a) it's not very elegant. Already you are writing an except block that literally catches anything which is a bad practice.
b) tells me that you don't quite understand how to use WebDriverWait since that's exactly what this class is for.

It sounds like there are two questions in this first part:

1. Can I _extend_ Pylenium?
2. How do write my own custom functions of Pylenium commands?

## Can I _extend_ Pylenium?

Short answer is yes, but you would need to understand OOP with Python in order to do that which is outside of the scope of this project.

For someone starting out, it would be much easier to create your own custom functions as needed which leads to...

## How do I write my own custom functions of Pylenium commands?

This is the example you gave:

```python
py.get_ignore_exception_then_retry('div > h1').should().contain_text('Redfern')
```

Kind of like what I said in the section above this, you just need to understand OOP. Without using inheritance and polymorphism, you won't be able to extend the Pylenium class to "add functions" directly to `py.`, but that's ok. Like I said, for now you should focus on just creating the function in a different module so you can re-use it in many places.

I mention needing to understand basic OOP because which object has the ability to call `.should()`?
Which object has the ability to call `.contain_text()`?
You asking this question tells me that there are programming basics and principles that you don't quite have yet, which is ok, but is _not_ a limitation of Pylenium but a current limitation of your understanding.

To give some help, the `Pylenium`, `Element`, and `Elements` classes each have their own `Should` class with helpful functions for most cases. So if you wanted to write your own function to get an `Element`, then all you need to do is have that function return an `Element`. That's it.

> The chaining that you see is not a feature of Pylenium, but of Python and a technique used in OOP

When you create an instance of WebDriverWait, you can specify `timeout`, `ignore_exceptions`, and then literally _any_ condition(s) to wait for. This should remove the need for any try/except when it comes to synchronizing with the browser. By default, Selenium will only ignore `NoSuchElementException`, but you can add to this list.

```python
# add it to your custom waits
py.wait(ignored_exceptions=[StaleElementReferenceException]).until(whatever)

# add it to the .should() expectation
py.get('#foo').should(ignored_exceptions=[StaleElementReference]).contain_text('bar')
```

This would remove the need for the example you had, but you can literally wrap anything into your own custom function. It won't be added to Pylenium, but for now, I don't think that's a problem 😄 

```python
# this is better than trying to add it to `py.`
# also, while I'm here, this function name hides which exceptions you are ignoring AND doesn't tell the reader that you're getting a single element
get_ignore_exception_then_retry('div > h1').should().contain_text('Redfern')
```

# Section 2

> I understand that we should isolate tests from each other, even though initialising browser can take up to 40-60% test time and we have tens or hundreds of tests.

40%-60% sounds like an exaggeration. At the very least, that has never been my experience. Most of our tests at the UI layer take about 10-30 seconds. Using percentages, if the browser took 2 seconds to spin up and then the test itself took 8 seconds, yeah, the 20% spin-up time sounds like a lot. Such is the nature of using percentages and using UI Automation haha.

> Or sometimes we have multiple tests which require login step which will take even longer time. We still should not share driver between these tests and keep them modular (in this case each time start from logging in), correct?

In my previous answer I talked about creating ways to bypass the login or "shortcut" to the location and state to begin your test. Being logged in is not something you have to do through the UI and you _really_ shouldn't want to. The only tests that should be concerned with the Login UI are the Login Tests that are specifically testing it.

Anything else that needs to be logged in can just bypass it with something as simple as an API call or setting a cookie (depends on how y'all do your authentication and things). This would mean that the act of logging in takes 1 second maximum!

Leveraging things like your HTTP APIs is crucial in the Automation in Testing game. You can literally inject any data or state you want into your application so you don't have to do that manually in the UI. For example, we could inject items into a Cart with an API call and then land on the Cart page (already logged in) to then complete the purchase. Loading my cart would only take a couple seconds and the UI part wouldn't take long either. You gotta get innovative and creative with this stuff - especially as an Automation Engineer!

> What if I want to implement end-2-end test with multiple actions which real users will be likely performing (for example, visit page, search listing, click on listing, add to cart, find another listing, add to cart, go to checkout, complete checkout)? Is it ok to include multiple assertions along the path?

Sure! That is better than making tests dependent on each other. I'm not a fan of these types of tests, but it's a single flow that you are testing, so make it a single test.

**Comment by MaksimZinovev** [comment]
@ElSnoMan thank you so much for your answers! That's very helpful and detailed response. 
Most articles, tutorials and  and courses  I  was using that  teach how to use Selenium usually provide simple examples and very basic tests. Once you try to write your own code you face lots of surprises and obstacles. Taking into account your comments, I now see that  googling and reading stackoverflow answers can sometimes lead you to bad practices (like that example with try/except block). Also sometimes i find myself overcomplicating things. I definitely need to learn to get rid of this habit...

> When you create an instance of WebDriverWait, you can specify timeout, ignore_exceptions, and then literally any condition(s) to wait for. This should remove the need for any try/except when it comes to synchronizing with the browser. By default, Selenium will only ignore NoSuchElementException, but you can add to this list.

So, it seems like I should aim for using the above to fix my problem with   StaleElementReferenceException. 

Injecting data and state with API calls is probably  more advanced techniques which  I yet have to learn.

Once again, thank you for response and sharing on GitHub your Twich challenges. There's nothing better than real life examples! 
Would be much appreciated if you could share any useful links related to this discussion. Cheers 🙂

**Comment by ElSnoMan** [comment]
@MaksimZinovev 

> Most articles, tutorials and and courses I was using that teach how to use Selenium usually provide simple examples and very basic tests.

I know exactly what you mean with the tutorials and things. They are great for getting started, but they quickly become obsolete haha. This is much worse in the Testing world because not many testers are good programmers... but I digress.

> Once you try to write your own code you face lots of surprises and obstacles.

Pylenium was built so you are almost "forced" to write your tests and Testing Solution using better practices. For example, the approach you were taking by making tests dependent on each other would have prevented you from using scaling solutions like Docker and Selenium Grid. That would have sucked if you spent a bunch of time building it just to find out that it doesn't work and then have to redo everything. Ouch.

On my Twitch Stream, we have been working with David to get his POC in a great place so he can go up for a promotion to an SDET at his company. We started the project from scratch and have been using all of the techniques we're mentioning here. He is now doing a lot of the heavy lifting via the HTTP APIs instead of the UI which is saving a ton of time in each test and makes them more stable. You should watch one of these days and ask a bunch of questions in chat! I'm sure he'd love to share his solution 👍 

Which brings me to my next point: Keep asking questions, but try doing it in a more public forum or community. For example, join the Ministry of Testing or Test Automation University Slack Groups! We have awesome people that can answer your questions. Different experiences and perspectives will be super valuable to you as you continue on this journey 😄 Take advantage of all the many resources that exist, but especially the community!

> Taking into account your comments, I now see that googling and reading stackoverflow answers can sometimes lead you to bad practices (like that example with try/except block). Also sometimes i find myself overcomplicating things. I definitely need to learn to get rid of this habit...

This is a tough one and really comes easier with more practice and experience. As you continue learning, you're creating your own opinions, biases, etc. about all of this stuff. This is another reason why having a community is so valuable because you can bounce ideas off of them so you can form a more "educated" opinion rather than from a single Stack Overflow response. (I'm sure you've even seen that the "right answer" on Stack Overflow isn't always the highest rated one.)

Also know that keeping things simple can be very difficult. Words like "simple" and "quality" are highly subjective, but you need to know the difference between simple code and complicated code so you can actually start writing code that leans closer to the simple side.

```
DIRTY CODE (-100)                            0                              (100) CLEAN CODE
<--------------------------------------- your code ---------------------------------------->
```

Using the simple 1-dimensional graph above, whenever you write a function, class, or test, where would you place that code on this graph?

* -100 would be really bad code. Messy, complicated, hard to read and understand, etc. You may have heard things like "spaghetti code" haha.
* 0 is "meh" code. This is most likely your first crack at solving the problem - kinda like a first draft.
* 100 is the cleanest code. In purist form, this would essentially mean that you can't really refactor or change it to be better.

In order for you to put your code on this graph, you need to have an understanding of what Dirty vs Clean is. Without that, you would blindly place your rating on the graph. You suggest this at the end, but to help you understand this, you need to work with the community to see examples of bad code vs good code. Bad tests vs good tests. If you were to put a rating of some code in the Dirty section, let's say a rating of -80, then that means you understand what makes it Dirty which would also mean you know how to clean it up to raise the rating. Pretty cool stuff.

> So, it seems like I should try the above to fix my problem with `StaleElementReferenceException`.

In theory, that should work.

> Injecting data and state with API calls is probably more advanced techniques which I yet have to learn.

It's more of understanding how HTTP APIs work and their purpose in the application your testing. Once you understand that, the rest kind of falls into place. This is where things like Postman can be really helpful.

> Once again, thank you for response and sharing on GitHub your Twitch challenges. Do you still accept new challenges? There's nothing better than real life examples to learn from!
Would be much appreciated if you could share any useful links related to this discussion. Cheers 🙂

I always accept questions and challenges for the Twitch Stream 😃 . Most of the links I'd provide would be courses on testautomationu.com, so I'd suggest going there and looking at some learning paths!
