### ISSUE TITLE
Logging not writing to test_results directory

### ISSUE THREAD

**Issue by pmneve** [ElSnoMan/pyleniumio#163]
The test_results sub-directories for the test methods are created but no files appear in them.

from pylenium conftest.py:

`@pytest.fixture(scope='session')
def py_config(project_root, request) -> PyleniumConfig:
    """ Initialize a PyleniumConfig for each test..."""
    try:
        # 1. Load pylenium.json in Project Root, if available
        with open(f'{project_root}/pylenium.json') as file:
            _json = json.load(file)
        **config = PyleniumConfig(**_json)**
    except FileNotFoundError:
        # 2. pylenium.json not found, proceed with defaults
        config = PyleniumConfig()
`
config.logging shows pylog_level='debug' and screenshots_on=True
No cli options supplied either for pylenium or pytest.

When this is executed:
`    # Logging Settings
    cli_pylog_level = request.config.getoption('--pylog_level')
    if cli_pylog_level:
        config.logging.pylog_level = cli_pylog_level
`
config.logging still shows pylog_level='debug' and screenshots_on=True

All of the Logger entries in py.log.manager.loggerDict show RootLogger level 20 (INFO) 
The logger associated with the pylenium conftest.py shows what looks to be an override to DEBUG (as in the pylenium.json file)

pylenium.json:
`{
  "driver": {
    "browser": "chrome",
    "remote_url": "",
    "wait_time": 15,
    "page_load_wait_time": 15,
    "options": [],
    "capabilities": {},
    "version": "latest",
    "experimental_options": null,
    "extension_paths": [],
    "local_path": ""
  },

  "logging":{
    "screenshots_on": true,
    "pylog_level": "debug"
  },

  "viewport": {
    "maximize": false,
    "width": 1440,
    "height": 900,
    "orientation": "portrait"
  }
}
`
INFO logging is seen in the console from 
`self.py.log.info("info log message")` only if 

`log_cli = True
log_cli_level = INFO
log_cli_date_format = %Y%m%d %H:%M:%S
log_cli_format = %(asctime)s %(levelname)s %(message)s
`
is present in pytest.ini

What am I missing and what else do you need to see to get a handle on this?

**Comment by ElSnoMan** [comment]
1. Screenshots only appear in the respective test's result folder on test failure, so this is expected behavior.

2. Pylenium uses Python's built-in `logging` module. We switched over to that (a long time ago) because
   a) it's the recommended approach
   b) it allows the user to handle the logging in a familiar manner with a lot more extensibility and control. For example, many CI tools can hook into reading/writing the logs which is usually better than a .txt artifact.

We actually have a task to remove the `test_results` directory altogether since there can be race conditions depending how the tests and/or framework around them are authored.

This all looks like expected behavior, but it seems like this was unclear so I'm sure there's better ways we can make this visible and easier to understand

**Comment by pmneve** [comment]
I do believe the docs need updating in this area.  Was trying to follow them.  I did do some debug breakpoints and got logging itself to work (as noted above).  As I'm using a docker container access to the logs and capturing them to a file/artifact is possible if necessary.  Thanks again for your quick and thorough response!! 
Am liking pylenium quite a bit so far.  Integrating Page Objects and running in docker container is straightforward (even for a docker neophyte like me!)  Please keep up the good work!

**Comment by pmneve** [comment]
Closing this as I've gotten logging to work with the usually pytest.ini entries for log_cli.
Thanks, again!
