### ISSUE TITLE
Use Selenium 4's new Action class changes for Click and Drag

### ISSUE THREAD

**Issue by vernko** [ElSnoMan/pyleniumio#174]
Selenium 4 made additions to the `Actions` class:

- click() replaces moveToElement(onElement).click()
- doubleClick() replaces moveToElement(onElement).doubleClick()
- contextClick() replaces moveToElement(onElement).contextClick()
- clickAndHold() replaces moveToElement(onElement).clickAndHold()
- release() moved from org.openqa.selenium.interactions.ButtonReleaseAction to Actions class

**Comment by ElSnoMan** [comment]
Darn. The Selenium4 Actions for drag and drop at least show things being dragged around, but it's still inaccurate and buggy...

- I'm testing this against: https://the-internet.herokuapp.com/drag_and_drop
- and using Selenium's official docs: https://www.selenium.dev/documentation/webdriver/actions_api/mouse/

The `test_drag_and_drop` tests we have fail when I use the new functionality, so I'm going to close this ticket since our jquery solution works well
