### ISSUE TITLE
version not updated in pyproject.toml

### ISSUE THREAD

**Issue by sugatoray** [ElSnoMan/pyleniumio#230]
The current version in `pyproject.toml` is `1.12.8`, and not `1.13.0`. Is this a bug?

PyPI: https://pypi.org/project/pyleniumio/#history

source: 

https://github.com/ElSnoMan/pyleniumio/blob/79373c984a48091487f39906358c705c21bf2ee2/pyproject.toml#L1-L6

**Comment by sugatoray** [comment]
cc: @ElSnoMan

**Comment by ElSnoMan** [comment]
Hi @sugatoray,

Nice catch! It's not _technically_ a bug 🐛 , but I think it's misleading. We have a `publish` CI pipeline that publishes a specific version of `pyleniumio` to `pypi` and it doesn't use the version in `pyproject.toml`.

So, we either update it manually before the release or we figure out an automated way to handle it - ideally in that pipeline.

What do you think?

**Comment by sugatoray** [comment]
One option (perhaps the simplest one) is to just **remove** the line with package `version` under metadata in `pyproject.toml`. Since, you are dynamically specifying the version in `setup.py`, this should not create any problem while releasing to pypi.

**Comment by ElSnoMan** [comment]
@sugatoray

When I attempt to delete the `version` field under `[tool.poetry]`, I receive an error saying it's a _required_ field.

![image](https://user-images.githubusercontent.com/23081277/151864546-e1513056-35e6-41c2-99f1-bf4d1496d431.png)

I'm thinking I could leave it blank, but not sure if that's a "bad practice" or not (or if it even matters). Thoughts?

**Comment by sugatoray** [comment]
Okay. Then you may need to read the file and get the version (in setup.py) from that version field in `pyproject.toml`. 

You could update the GitHub action that bumps version, to change the version field in `pyproject.toml`.

**Comment by sugatoray** [comment]
About leaving it blank, I am not sure if that's possible or not. You could give it a shot and try pushing a test release to testpypi (instead of pypi) to see if it works or not.

**Comment by ElSnoMan** [comment]
Can't leave it blank, but you're more than welcome to create a PR with a
solution.

I won't get to it for a while since it's low priority.

**Comment by rnestler** [comment]
How important is it to you that the version is generated in the release pipeline? I'd suggest to keep it manually at one place (pyproject.toml) and verify in the release pipeline, that the tag matches the version there and abort if it doesn't match. So the release process would look like this:
 * Manually update the version in pyproject.toml (and push the commit)
 * push the version tag
 * Pipeline runs, verifies that the tag matches the version in `pyproject.toml`
 
 Also would you consider building and publishing with poetry directly and get rid of `setup.py` entirely? https://python-poetry.org/docs/libraries/#packaging
 
 Because currently the dependencies are specified differently in pyproject.toml and setup.py, leading to issues such as #246

**Comment by ElSnoMan** [comment]
Ultimately, I would like to use Poetry to do this but I haven't had time to get to it yet. As always, PRs are welcome 😄

**Comment by ElSnoMan** [comment]
Closing this issue in favor of #277 - This is getting closer to the top of my list 😄
