### ISSUE TITLE
`find_element_by_*` deprecation warning

### ISSUE THREAD

**Issue by lolrenx** [ElSnoMan/pyleniumio#240]
`find_element_by_*`  is being deprecated in favor of 

```
from selenium.webdriver.common.by import By
...
fnd_btn = driver.find_element(By.CLASS_NAME, "your_class_name")
```

hopefully this can be implemented without introducing a direct dependency to `from selenium.webdriver.common.by import By`

**Comment by ElSnoMan** [comment]
Which version of Pylenium are you using?

**Comment by lolrenx** [comment]
`pyleniumio==1.14.2`

**Comment by ElSnoMan** [comment]
Can you share some code, traces, and logs because that was taken care of in an earlier release? I recommend upgrading to `1.14.3` for other deprecation warnings we resolved, but that was for `webdriver_factory`

**Comment by lolrenx** [comment]
sure, here's the strack trace : 

```
test_sidebar.py:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
    toggler = py.wait(use_py=True).until(lambda x: x.find_element_by_id("menu-btn"))
```

and test code : 

```
@pytest.mark.usefixtures("admin_user")
def test_toggle_sidebar(py, live_server, admin_user: Users) -> None:
    login_admin(py, live_server, admin_user)
    toggler = py.wait(use_py=True).until(lambda x: x.find_element_by_id("menu-btn"))
    sidebar = py.wait(use_py=True).until(lambda x: x.find_element_by_id("sidebar"))
    assert sidebar.is_displayed()
    toggler.click()
    assert not sidebar.is_displayed()
    toggler.click()
    assert sidebar.is_displayed()
```

I'm sure using `driver.find_element(By.CLASS_NAME, "your_class_name")` solved that but that means depending directly on selenium's webdriver. I'd rather use pylenium's implementation instead

**Comment by ElSnoMan** [comment]
You're right about the documentation and that is something I will be working on soon since there are pages that are outdated since the release of Pylenium `v1.15.1`. I made sure to include the examples on the `WebDriverWait` page, so thanks for catching that!

As for your code, Pylenium allows you to access the `WebDriver` instance whenever you need it. If you use their deprecated methods, then yeah, you'll get deprecation warnings. Pylenium may not have **_every scenario_** and use-case covered, so it's nice that the user has flexibility there.

However, for what your test is doing, you should be able to get away with only Pylenium things:

```python
@pytest.mark.usefixtures("admin_user")
def test_toggle_sidebar(py, live_server, admin_user: Users) -> None:
    login_admin(py, live_server, admin_user)
    toggler = py.get("menu-btn")
    sidebar = py.get("sidebar").should().be_visible()
	
    toggler.click()
    assert sidebar.should().disappear()

    toggler.click()
    assert sidebar.should().be_visible()
```

**Comment by lolrenx** [comment]
thanks a lot, that makes sense ! 
and also thanks for the quick response and the insight into the pylenium proper syntax, this is very fluent and miles away from the clunky selenium syntax. Keep it up, your work is very appreciated 👍
