### ISSUE TITLE
Support webdriver-manager 3.8.6 auto detection

### ISSUE THREAD

**Issue by rnestler** [ElSnoMan/pyleniumio#298]
According to https://github.com/SergeyPirogov/webdriver_manager/releases/tag/v3.8.6 webdriver-manager supports an auto-detection mode if no version is specified:
`if version is None - tries to determine installed browser version, and if fail - downloads like "latest" - LATEST_RELEASE.`

But it seems that pylenium doesn't support setting no version and seems to pass "latest" if no version is specified.

**Comment by ElSnoMan** [comment]
Thanks for calling this out! I'm labeling this as a bug since our implementation of driver version works for some and not for others. I'll update this so we take full advantage of how webdriver_manager does things.

I haven't switched to Selenium's "Selenium Manager" yet because it still has a lot of issues, but I'm assuming that will be the solution we move to eventually.

**Comment by ElSnoMan** [comment]
https://github.com/ElSnoMan/pyleniumio/releases/tag/v1.18.0
