### ISSUE TITLE
[Question] Can we use pyleniumio with other test runner?

### ISSUE THREAD

**Issue by idxn** [ElSnoMan/pyleniumio#65]
It would be great if we can use pyleniumio for web scrapping or any other test runner/framework. It will gain more people to contribute more into the project as well.

**Comment by ElSnoMan** [comment]
For Pylenium to have its ease-of-use, I had to use pytest which is really the only testing framework you should be using with Python anyway. If you want to do web scraping, just use Selenium. Pylenium is 100% meant for automated UI tests so I won't be looking to integrate it with other testing frameworks like UnitTest

**Comment by ElSnoMan** [comment]
Currently, you _can_ make an instance of `Pylenium` to do things like web scraping, or you can just make an instance of `WebDriver since `Selenium` is already included in `Pylenium`.

To make an instance of Pylenium, this is what you need:

```python
    def __init__(self, config: PyleniumConfig, logger: Logger):
        self.config = config
        self.log = logger
```

aka you need an instance of `PyleniumConfig` and an instance of `Logger`. That's easy to do if you know how to instantiate these classes. Otherwise, I would honestly just recommend using Selenium.

I'll be closing out this Issue since using Pylenium outside of tests is not what it's meant for and using pytest is a very strategic and calculated move. Thank you for your feedback!

**Comment by idxn** [comment]
Thanks a lot. I'll try that out :)
